project:
  type: website
  output-dir: docs

website:
  title: "Práctica Git-Git Hub Maevolab"
  favicon: maevolab.png
  
  navbar:
    background: "#01497c"
    logo: cursologo.png
    pinned: true
    align: center
    left: 
      - href: index.qmd
        text: Inicio

  
  page-footer:

    right: "Maevolab- 2025"



format:
  html:
    theme: 
      light: [flatly, web_styles.scss]
    toc: true
    
execute:
  freeze: auto
